URL = localhost:5000/api/resource

GET:
	http GET $(URL)

PUT:
	http PUT $(URL)/500 data="I am definitely new data"

POST:
	http POST $(URL) data="this is my latest value"

DELETE:
	http DELETE $(URL)
